// Unused.
#![no_std]
#![allow(
    unsafe_op_in_unsafe_fn,
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    improper_ctypes,
    dead_code,
    unnecessary_transmutes,
    clippy::all
)]

// include!("../../../linux/rust/bindings/lib.rs");

// Include the file in the OUT_DIR generated by build.rs
mod bindings_raw {
    use pin_init::MaybeZeroable;
    type __kernel_size_t = usize;
    include!(concat!(env!("OUT_DIR"), "/bindings_generated.rs"));

    // Use glob import here to expose all helpers.
    // Symbols defined within the module will take precedence to the glob import.
    pub use super::bindings_helper::*;
}

// When both a directly exposed symbol and a helper exists for the same function,
// the directly exposed symbol is preferred and the helper becomes dead code, so
// ignore the warning here.
#[allow(dead_code)]
mod bindings_helper {
    // Import the generated bindings for types.
    use super::bindings_raw::*;
    include!(concat!(env!("OUT_DIR"), "/bindings_helpers_generated.rs"));
}

pub use bindings_raw::*;
